// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/approve-user': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/approve-user.post').default>>>>
    }
    '/api/admin/deactivate-user': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/deactivate-user.post').default>>>>
    }
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users.get').default>>>>
    }
    '/api/auth/session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/session.post').default>>>>
    }
    '/api/bugs/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bugs/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bugs/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bugs/[id].put').default>>>>
    }
    '/api/bugs/attachments/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bugs/attachments/[id].delete').default>>>>
    }
    '/api/bugs/attachments': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bugs/attachments/index.post').default>>>>
    }
    '/api/bugs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bugs/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bugs/index.post').default>>>>
    }
    '/api/bugs/metrics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bugs/metrics.get').default>>>>
    }
    '/api/bugs/open-for-test-case': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bugs/open-for-test-case.get').default>>>>
    }
    '/api/cron/daily-digest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/daily-digest.get').default>>>>
    }
    '/api/cron/daily-snapshot': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/daily-snapshot.get').default>>>>
    }
    '/api/dashboard/developer': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/developer.get').default>>>>
    }
    '/api/dashboard/metrics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/metrics.get').default>>>>
    }
    '/api/dashboard/scope': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/scope.get').default>>>>
    }
    '/api/developer/bugs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/developer/bugs.get').default>>>>
    }
    '/api/executions/:releaseId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/executions/[releaseId].get').default>>>>
    }
    '/api/executions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/executions/index.post').default>>>>
    }
    '/api/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/me.get').default>>>>
    }
    '/api/modules/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/modules/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/modules/[id].put').default>>>>
    }
    '/api/modules': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/modules/index').default>>>>
    }
    '/api/profile/digest-preview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/digest-preview.get').default>>>>
    }
    '/api/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/index.put').default>>>>
    }
    '/api/releases/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/releases/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/releases/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/releases/[id].put').default>>>>
    }
    '/api/releases/:id/test-cases': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/releases/[id]/test-cases.post').default>>>>
    }
    '/api/releases': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/releases/index').default>>>>
    }
    '/api/requirements/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/requirements/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/requirements/[id].put').default>>>>
    }
    '/api/requirements': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/requirements/index').default>>>>
    }
    '/api/test-cases/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test-cases/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test-cases/[id].put').default>>>>
    }
    '/api/test-cases/:id/duplicate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test-cases/[id]/duplicate.post').default>>>>
    }
    '/api/test-cases': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test-cases/index').default>>>>
    }
    '/api/users/:id/approve': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/approve.post').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
    }
    '/api/users/pending': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/pending.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}