// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/18/2026, 2:56:10 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/dev/bookmeqa/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/dev/bookmeqa/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/dev/bookmeqa/app/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/dev/bookmeqa/app/plugins/**/*.{js,ts,mjs}","C:/dev/bookmeqa/app/composables/**/*.{js,ts,mjs}","C:/dev/bookmeqa/app/utils/**/*.{js,ts,mjs}","C:/dev/bookmeqa/app/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/dev/bookmeqa/app/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/dev/bookmeqa/app/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/dev/bookmeqa/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;